### ISSUE TITLE
Metadata table not updated if not results for RGI

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida-plugin-amr-detection#8]
If no results for RGI are found, instead of updating the metadata table with the staramr results, I get the following exception:

```
16 Aug 2019 14:42:01,629 ERROR ca.corefacility.bioinformatics.irida.service.analysis.execution.galaxy.AnalysisExecutionServiceGalaxyAsync:229 - Error updating corresponding samples with analysis results for Anal
ysisSubmission = [8]. Skipping this step.                                               
ca.corefacility.bioinformatics.irida.exceptions.PostProcessingException: No results found in rgi output file [/Drives/W/Temporary/aaron/output-files/73/0/rgi-summary.tsv]
        at ca.corefacility.bioinformatics.irida.plugin.amrdetection.AMRDetectionUpdater.getRgiResults(AMRDetectionUpdater.java:174)
        at ca.corefacility.bioinformatics.irida.plugin.amrdetection.AMRDetectionUpdater.update(AMRDetectionUpdater.java:204)    
        at ca.corefacility.bioinformatics.irida.pipeline.results.impl.AnalysisSubmissionSampleProcessorImpl.updateSamples(AnalysisSubmissionSampleProcessorImpl.java:88)
...
```

**Comment by apetkau** [comment]
Fixed in #13 

Released as `0.2.0` - https://github.com/phac-nml/irida-plugin-amr-detection/releases/tag/0.2.0
